sudo: required
services:
  - docker

before_install:
  - docker build -t stefanprifti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stefanprifti/react-test npm test -- --coverage

after_success:
  - docker build -t stefanprifti/multi-client ./client
  - docker build -t stefanprifti/multi-nginx ./nginx
  - docker build -t stefanprifti/multi-server ./server
  - docker build -t stefanprifti/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push stefanprifti/multi-client
  - docker push stefanprifti/multi-nginx
  - docker push stefanprifti/multi-server
  - docker push stefanprifti/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Prod
  bucket_name: elasticbeanstalk-us-east-1-719080364157
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY